### PR TITLE
feat: upgrade to middy v2.x

### PR DESCRIPTION
**Pull request by theburningmonk**
## What did you implement:

Middy recently upgraded to v2, with some breaking changes. This PR brings us up to date with Middy.

## Todos:

- [x] Write tests
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** YES

### CODE REVIEW

**Comment by lkhari** [comment]
Nice, I was also looking into this, since I was thinking about changing our typing when I saw the middy update.

The problem I saw is this update is actually a breaking change:
* It breaks our typescript types- though this can be easily fixed and isn't a major blocker
* Our `pattern-` packages we return the middy object and since middy has breaking changes it most likely will pass down.
* Middy no longer supports node.js v10 but lambda and our CI still do

**Comment by theburningmonk** [comment]
@lkhari good shout, we should mark this as a breaking change instead.

Lambda is starting the deprecation process for node 10.x from July so it shouldn't be a big issue, but middlewares that worked with it previously would need to upgrade to the middy 2.0 interface (e.g. no more `next`)

**Comment by theburningmonk** [comment]
@lkhari @gsingh1 I've updated the PR to mark the PR as breaking, so hopefully lerna would see as breaking change and publish a new major version. I've removed test-node10 from the CI config as well since middy has dropped support for Node.10 and Lambda is deprecating it soon as well.

**Comment by lkhari** [comment]
Seems good, to me, I've made a PR for this feature branch that contains typings to reflect more closely with what middy has written. I've exposed Contexts as one of the generics since a few of our patterns put the data in the context object.

But I'm not a maintainer so I'll leave that up to you @gsingh1 ! 😄

**Comment by gsingh1** [comment]
This is awesome, thanks @theburningmonk. We should probably add a node14 in the CI. It would be good to add a note in the readme about the node runtimes that we support too.

**Review by gsingh1 — APPROVED** [review]

**Comment by demsey2** [comment]
ci/circleci: test-node10 hasn't completed but it looks like middy 2.0 dropped support for node 10 https://middy.js.org/docs/UPGRADE.html

**Comment by theburningmonk** [comment]
@demsey2 I disabled node10 in this PR, which is why the node10 is not running, but looks like the checks is not respecting that, maybe it needs to be configured elsewhere?

@gsingh1 @simontabor do you guys know?

**Comment by demsey2** [comment]
There is another problem, I am testing that and it looks like MiddlewareObj interface changed the signature, it was

```
 MiddlewareObject<T, R, C extends Context = Context>
```
and now we have 
```
MiddlewareObj<TEvent = any, TResult = any, TErr = Error>
```

not sure why they did remove the Context but that is probably a question we should ask them

**Comment by theburningmonk** [comment]
@demsey2 if you refer to middy's [documentation](https://github.com/middyjs/middy) there's some examples of what the middleware accepts now - essentially just a `request` object, no more `next`.

As @lkhari noted, this affects anyone who writes custom middlewares and use them with the built-in patterns, which is why I made a dummy commit to make this PR a breaking change.

**Comment by demsey2** [comment]
@theburningmonk the problem is that definition, 

```
export default function <T, R, C extends Context = Context>(params: {
  sampleDebugLogRate: number;
}): middy.MiddlewareObj<T, R, C>;
```
it should be 
```
export default function <T, R, E extends Error>(params: {
  sampleDebugLogRate: number;
}): middy.MiddlewareObj<T, R, E>;
```
because this is the definition of middy.middlewareObj
```
MiddlewareObj<TEvent = any, TResult = any, TErr = Error>
```
they have removed Context and now they always use LambdaContext
this is the previous version
```
MiddlewareObject<T, R, C extends Context = Context>
```

**Comment by lkhari** [comment]
Whoops. Yea @demsey2  is correct. I must have just updated the middy object name, but missed out the correct generics there. I was probably more focused on exposing the context for our other stuff.

If you change `packages/lambda-powertools-middleware-correlation-ids/index.d.ts` lines 15 -17 to look like below, then it should fix the issue:

```
export default function <TEvent = any, TResult = any, TErr = Error>(params: {
  sampleDebugLogRate: number;
}): middy.MiddlewareObj<TEvent, TResult, TErr>;
```

**Comment by simontabor** [comment]
@theburningmonk I've disabled the required check for node:10, so you're all green now. I'll add node:14 as required as soon as it's added too

**Comment by theburningmonk** [comment]
thanks @simontabor and @lkhari!

**Pull request merged**
