### PR TITLE
chore: fix CI by including _book directory

### PR DESCRIPTION
**Pull request by loujaybee**
## What did you implement:

The previous build failed because: 

https://circleci.com/gh/getndazn/dazn-lambda-powertools/1056

In order to push the contents of the directory to `gh-pages` branch, the directory must be known to github (See [this issue on StackOverflow](https://stackoverflow.com/questions/33832046/git-subtree-split-no-new-revisions-were-found)) and the contents not ignored (otherwise the ignored files are not pushed). This means that we also have to temporarily add and commit (in CI) the new book files, before pushing. Frustratingly, Github also doesn't allow you to commit empty directories, so I've added an empty file to the directory (See [this issue on StackOverflow](https://stackoverflow.com/questions/4250063/how-to-gitignore-all-files-folder-in-a-folder-but-not-the-folder-itself))

After running locally this appears to be working: https://getndazn.github.io/dazn-lambda-powertools/

## How did you implement it:

As above. 

## How can we verify it:

Unsure, I think only with push to master

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / projects / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by loujaybee** [comment]
Thanks for the review @theburningmonk — I've actually since updated the PR if you wanted to take a look. I really wanted to avoid force pushing, but since we're mangling history it seems there's no true idempotent way to get around the problem. The current implementation (whilst not very elegant) at least seems to work repeatably. You can run on your own machine to verify.

**Comment by theburningmonk** [comment]
@loujaybee it looks good

**Comment by theburningmonk** [comment]
@gsingh1 we need to add a white background to the image though, it's hard to see the lines on the docs

**Comment by loujaybee** [comment]
@theburningmonk agree'd — I wanted to get the docs up first, now I'll go through and make those additional changes in subsequent PR's, thanks for the quick reviews! ❤️

**Pull request merged**
