### PR TITLE
feat(logger): added support BigInt

### LINKED ISSUE #147: Logger fails if object contains BigInt value as JSON.stringify() does not support BigInt data type
# This is a Bug Report

## Description
Very large numbers coming for instance from a DynamoDB table are handled as BigInt values since a few days. Unfortunately, JSON.stringify() does not support converting BigInt values.

* What went wrong?
log.debug("test message", { number: 1n}) results into an error

* What did you expect should have happened?
* What was the config (if any) you used?
* What stacktrace or error message did you see?
...
 TypeError: Do not know how to serialize a BigInt
        at JSON.stringify (<anonymous>)
        at Logger.log (.../node_modules/@dazn/lambda-powertools-logger/index.js:75:22)
        at Logger.debug (.../node_modules/@dazn/lambda-powertools-logger/index.js:79:10)
...
Similar or dependent issues:
* #12345

## Additional Data

* ***Which powertool package are you using?***:
  "@dazn/lambda-powertools-logger": "^1.15.2"   
* ***Which version are you using?***:
1.15.2
* ***Middy engine version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

### PR DESCRIPTION
**Pull request by lkhari**
## What did you implement:
Serialized BigInt values into strings
Closes #147

## How did you implement it:
Serialized the big int values to strings

## How can we verify it:
Unit Tests

## Todos:

- [x] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [ ] Provide verification config / projects / resources
- [X] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by lkhari** [comment]
> 
> 
> oh wait, sorry, just realised the commit messages don't follow conventional commit. Since we use semantic-release, we need the commit messages to follow [conventional commit](https://www.conventionalcommits.org/en/v1.0.0)

Thanks for the tip, i've changed the commit accordingly. I also ran the linting, and realised, the version of linting used doesn't accept BigInt. I've updated it in the commit. But due to upgrade style changes, a lot of other packages are failing.

Would you rather we put in a config to keep old style settings or would you like me to update the style in the packages to match the new settings.

**Comment by theburningmonk** [comment]
@lkhari can you see if you can keep the old style settings so we don't suddenly change a lot of the code that aren't related to this change? we can change the settings again later if they make more sense, but I'd rather that be a decisions more people get involved with

**Comment by lkhari** [comment]
This failed on node8 because bigInt native type was introduce in node10. AWS Lambda doesn't support node8 as of Feburary 24th.

**Comment by theburningmonk** [comment]
@lkhari yeah, we were just talking about disabling node8 tests as well

**Comment by theburningmonk** [comment]
can you remove the node8 tests in the circleci config?

**Pull request merged**
